# Generated by Django 3.2.11 on 2022-07-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr', models.FloatField()),
                ('media_simples', models.FloatField()),
                ('total_eletivas', models.FloatField()),
                ('curso', models.CharField(max_length=60)),
            ],
        ),
    ]
